Create array with numpy

In [14]:
import numpy as np

In [15]:
# creat a matrix and the discription of a matrix
array=np.array([[1,2,3],
                [2,3,4]])
print(array)
print('number of dim:',array.ndim)
print('shape：',array.shape)
print('size：',array.size)

[[1 2 3]
 [2 3 4]]
number of dim: 2
shape： (2, 3)
size： 6


In [16]:
#some useful method of creating numpy matrix
a=np.array([ [2,3,4],
             [2,3,2] ])  
b=np.zeros((3,4))
c=np.ones((3,4),dtype=np.int16)
d=np.empty((3,4))  #it's not exactly a empty matrxi
print(a)
print(b)
print(c)
print(d)

[[2 3 4]
 [2 3 2]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [17]:
e=np.arange(10,20,2)
f=np.arange(12).reshape(3,4)
g=np.linspace(0,10,20)  
print(e)
print(f)
print(g)

[10 12 14 16 18]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[  0.           0.52631579   1.05263158   1.57894737   2.10526316
   2.63157895   3.15789474   3.68421053   4.21052632   4.73684211
   5.26315789   5.78947368   6.31578947   6.84210526   7.36842105
   7.89473684   8.42105263   8.94736842   9.47368421  10.        ]


Numpy 的基础运算1

In [18]:
a=np.array([10,20,30,40])
b=np.arange(4)
print(a,b)

[10 20 30 40] [0 1 2 3]


In [19]:
c=b**2  
print(c)

[0 1 4 9]


In [20]:
d=10*np.sin(a)
print(d)

[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [21]:
print(b<3)   #bool

[ True  True  True False]


In [22]:
print(b==3)

[False False False  True]


In [25]:
e=np.array([[1,1],
           [0,1]])
f=np.arange(4).reshape((2,2))
g=e*f
g_dot=np.dot(e,f)
g_dot_2=e.dot(f)
print(g)
print(g_dot)
print(g_dot_2)
#这两种计算结果是不同的，矩阵运算需要使用第二种方法

[[0 1]
 [0 3]]
[[2 4]
 [2 3]]
[[2 4]
 [2 3]]


In [29]:
a=np.random.random((2,4))
print(a)
print(np.sum(a))
print(np.sum(a,axis=1)) 
####axis=1是在行方向，axis=0是在列方向
print(np.sum(a,axis=0))
print(np.max(a))

[[ 0.51548741  0.48708982  0.80026739  0.52214235]
 [ 0.83155473  0.06031829  0.49006617  0.42362322]]
4.13054936828
[ 2.32498697  1.8055624 ]
[ 1.34704214  0.5474081   1.29033355  0.94576557]
0.831554728282


Numpy 的基础运算2

In [31]:
A=np.arange(2,14).reshape(3,4)
print(A)
print(np.argmin(A))
print(np.argmax(A))  
#print the index of thenumber
print(np.mean(A))
print(A.mean())
print(np.median(A))  

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
11
7.5
7.5
7.5


In [32]:
print(A)
print(np.cumsum(A))
#逐步打印出来

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[ 2  5  9 14 20 27 35 44 54 65 77 90]


In [36]:
print(A)
print(np.diff(A))
#矩阵按行计算diff

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [38]:
B=np.arange(14,2,-1).reshape((3,4))
print(B)
print(np.sort(A))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [39]:
print(np.transpose(B))
print(B.T)
#矩阵的转置

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


In [40]:
print((A.T).dot(A))
#矩阵运算中经常会用到

[[140 158 176 194]
 [158 179 200 221]
 [176 200 224 248]
 [194 221 248 275]]


In [41]:
print(B)
print(np.clip(A,5,9))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[5 5 5 5]
 [6 7 8 9]
 [9 9 9 9]]


Numpy 索引

In [42]:
A=np.arange(3,15)
print(A)
print(A[3])

[ 3  4  5  6  7  8  9 10 11 12 13 14]
6


In [44]:
B=np.arange(3,15).reshape(3,4)
print(B)
print(B[2])
print(B[2][1])
print(B[2,1])

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]
12
12


In [46]:
print(B[1,:])
print(B[:,1])
print(B[1,1:3])

[ 7  8  9 10]
[ 4  8 12]
[8 9]


In [47]:
for row in B:
    print (row)
#可以直接print出来

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [48]:
for column in B.T:
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [49]:
print(B.flatten())
for item in B.flat:
    print(item)
#.flatten 返回的是list， .flat返回的是迭代器（Generator）

[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14
