In [2]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])
print(A)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [2]:
cal = A.sum(axis =0)
print(cal)

[  59.   239.   155.4   76.9]


In [6]:
percentage1 = 100*A/(cal.reshape(1,4))
percentage2 = 100*A/cal
print(percentage1)
print(percentage2)

[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]
[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


We ues reshape function to make sure the shape of matrix is exactly what we want.

In [7]:
a = np.array([[1],
            [2],
            [3],
            [4]])
b = 100
c = a+b
print(c)

[[101]
 [102]
 [103]
 [104]]


In [8]:
a = np.array([[1,2,3],
             [4,5,6]])
b = np.array([100,200,300])
c = a+b
print(c)

[[101 202 303]
 [104 205 306]]


In [9]:
a = np.array([[1,2,3],
             [4,5,6]])
b = np.array([[100],
              [200]])
c = a+b
print(c)

[[101 102 103]
 [204 205 206]]
