In [37]:
import numpy as np

image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

In [38]:
image[1,2,1]

0.27417312999999999

In [13]:
image.shape[]

(3, 3, 2)

In [9]:
image[1]

array([[ 0.92814219,  0.96677647],
       [ 0.85304703,  0.52351845],
       [ 0.19981397,  0.27417313]])

In [10]:
image[2]

array([[ 0.60659855,  0.00533165],
       [ 0.10820313,  0.49978937],
       [ 0.34144279,  0.94630077]])

In [11]:
image[0]*image[1]

array([[ 0.62952301,  0.28404261],
       [ 0.77384146,  0.27660436],
       [ 0.0842266 ,  0.12342603]])

In [12]:
image.reshape(18,1)

array([[ 0.67826139],
       [ 0.29380381],
       [ 0.90714982],
       [ 0.52835647],
       [ 0.4215251 ],
       [ 0.45017551],
       [ 0.92814219],
       [ 0.96677647],
       [ 0.85304703],
       [ 0.52351845],
       [ 0.19981397],
       [ 0.27417313],
       [ 0.60659855],
       [ 0.00533165],
       [ 0.10820313],
       [ 0.49978937],
       [ 0.34144279],
       [ 0.94630077]])

In [15]:
np.linalg.norm?

In [18]:
x = np.array([[0,3,4],
              [2,6,4]])
b= np.linalg.norm(x,axis=1,keepdims=True)
print(b)

[[ 5.        ]
 [ 7.48331477]]


In [19]:
x = np.array([
    [9, 2, 5, 0, 0],
    [7, 5, 0, 0 ,0]])
x_sum = x.sum(axis=1)
print(x_sum)

[16 12]


In [20]:
b = x/x_sum
print (b)

ValueError: operands could not be broadcast together with shapes (2,5) (2,) 

In [28]:
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

x3= np.multiply(x1,x2)
print(x3)

x4= x1*x1
print(x4)

[81  4 10  0  0 63 10  0  0  0 81  4 25  0  0]


TypeError: can't multiply sequence by non-int of type 'list'

In [30]:
x=4
w=np.zeros(4,1)
print(x)

TypeError: data type not understood

In [35]:
x1 = np.array([9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0])


TypeError: 'numpy.ndarray' object is not callable